name: slushbuster
description: A modern e-commerce Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  google_fonts: ^5.1.0
  animate_do: ^3.0.2
  shared_preferences: ^2.2.1
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  lottie: ^2.6.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_slidable: ^3.0.0
  cupertino_icons: ^1.0.5
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
